name: Hassan M. Yousuf
markdown: redcarpet
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: /HSY-Code